### ISSUE TITLE
The RM can edit a hierarchy while he shouldn't

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#523]
**List the CGR information**
- CGR version: 0.13.1
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
The RM can edit a hierarchy (add a geo-object type, remove one,...) while he shouldn't as per the rights by role matrix

**To Reproduce**
As the RM of the MOH
1. Go to the geo-object types and hierarchies module
2. Click on one of the hierarchy under the curation mandate of the Ministry of Health
3. Edit the hierarchy by adding a geo-object types, removing one, moving one,...
4. See the error: it is possible for the RM to edit a hierarchy under the curation mandate of the MOH

**Expected behavior (clear and concise)**
The RM CAN'T edit hierarchies as per the rights by role matrix

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Google Chome
 - Version: The most recent one

**Additional context (if any)**

**Comment by justinlewis** [comment]
@steeveebener I think we fixed this in Release 0.14.1. Can you double check?

**Comment by SteeveEbener** [comment]
I just tested this under staging (0.14.2) anc could remove a geo-object type from a hierarchy and then add a new one as a child => still an issue

**Comment by rrowlands** [comment]
Please re-test this on 0.14.5.

**Comment by SteeveEbener** [comment]
Just tested under 0.14.6 and it is working. I am closing this ticket
